export interface IRateEntity {
    Id: string;
    EstablishmentId: string;
    AverageRate: number | null;
    CountRate: number;
    AverageAtmosphere: number | null;
    CountAtmosphere: number;
    AverageFood: number | null;
    CountFood: number;
    AverageService: number | null;
    CountService: number;
    AverageValue: number | null;
    CountValue: number;
    AverageRooms: number | null;
    CountRooms: number;
    AveragePriceQuality: number | null;
    CountPriceQuality: number;
    AverageClean: number | null;
    CountClean: number;
    AverageLocation: number | null;
    CountLocation: number;
    AverageComfort: number | null;
    CountComfort: number;
    AverageAccessibility: number | null;
    CountAccessibility: number;
    AverageQuality: number | null;
    CountQuality: number;
    AverageSafety: number | null;
    CountSafety: number;
}
