export const mainlandData = [
    {
        key: "europe",
        title: "Европа",
        countries: ["arm", "by", "geo", "kz", "rus"],
    },
    {
        key: "asia",
        title: "Азия",
        countries: ["are", "tur"],
    },
    {
        key: "northAmerica",
        title: "Северная Америка",
        countries: [],
    },
    {
        key: "southAmerica",
        title: "Южная Америка",
        countries: [],
    },
    {
        key: "africa",
        title: "Африка",
        countries: [],
    },
    {
        key: "oceania",
        title: "Австралия и океания",
        countries: [],
    },
    {
        key: "antarctica",
        title: "Антарктида",
        countries: [],
    },
];
export const countriesData = [
    {
        id: "01H9ZAY3PNZ3TTN87P93F7QKGC",
        title: "Казахстан",
        value: "kazahstan",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "kz",
        flag: "kz.jpg",
    },
    {
        id: "01HMY6V2B1XZ0J3P5EQ9F2K4VG",
        title: "Россия",
        value: "russia",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "rus",
        flag: "rus.jpg",
    },
    {
        id: "01H9ZFTX89YTPD7QJW7N5EAWQP",
        title: "Беларусь",
        value: "belarus",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "by",
        flag: "by.png",
    },
    {
        id: "01H9ZFTW8P4BX5FK6NJ1C3RT39",
        title: "Армения",
        value: "armenia",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "arm",
        flag: "arm.png",
    },
    {
        id: "01HMY6V2B4YK8M9V4R6JQ3W5XT",
        title: "Грузия",
        value: "georgia",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "geo",
        flag: "geo.jpg",
    },
    {
        id: "01HMY6V2B3E5S7X8JQ0NH9T1DM",
        title: "ОАЭ",
        value: "uae",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "are",
        flag: "are.png",
    },
    {
        id: "01JQYKKCZ7MM92P1TF9VWWT16D",
        title: "Турция",
        value: "turkey",
        videoSrc: "/mock/polandVideoMock.mp4",
        posterSrc: "/mock/restMock.jpg",
        iso: "tur",
        flag: "tur.png",
    },
];
