export const CONSTANT_ARTICLE_STATUS_DB = {
    ARCHIVED: "ARCHIVED",
    DRAFT: "DRAFT",
    HIDDEN: "HIDDEN",
    PENDING_REVIEW: "PENDING_REVIEW",
    PUBLISHED: "PUBLISHED",
    REJECTED: "REJECTED",
    SCHEDULED: "SCHEDULED",
} as const;
