export const CONSTANT_CONSUMPTION_TYPE_CONTENT_DB = {
    ESTABLISHMENT: "ESTABLISHMENT",
    PUBLIC_ARTICLE: "PUBLIC_ARTICLE",
    BUSINESS_ARTICLE: "BUSINESS_ARTICLE",
} as const;

export const CONSTANT_CONSUMPTION_TYPE_DB = {
    SHARE: "SHARE",
    WATCH: "WATCH",
} as const;
