export const CONSTANT_RATES_ESTABLISHMENT_ARRAY_DB = [
    "Rooms",
    "PriceQuality",
    "Clean",
    "Location",
    "Rate",
    "Atmosphere",
    "Food",
    "Service",
    "Value",
    "Comfort",
    "Accessibility",
    "Quality",
    "Safety",
] as const;
