import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.scss";

import { Header } from "@/components/UI/Header/Header";
import { Footer } from "@/components/UI/Footer/Footer";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import ClientOnly from "@/components/UI/ATest/ClientOnly";
import { ToastProvider } from "@/components/UI/ATest/ToasterProvider";
import { IPageProps } from "@/types/IType";
import { locales } from "@/config";
import { ReactNode } from "react";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });
type Props = {
  children: ReactNode;
  params: { locale: string };
};
// export const metadata: Metadata = {
//   title: "Places Gold",
//   description: "Generated by create next app",
// };
export async function generateMetadata() {
  return {
    title: process.env.BASE_NAME,
  };
}
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
interface IRootLayoutProps extends IPageProps {
  children: React.ReactNode;
}
export default async function RootLayout({
  children,
  params: { locale },
}: IRootLayoutProps) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <link rel="icon" href="/icons/favicon small.svg" sizes="any" />

      <body className={inter.className}>
        <AntdRegistry>
          <NextIntlClientProvider messages={messages}>
            <Header />

            {/* <ClientOnly>
            <ToastProvider />
          </ClientOnly> */}
            <main>{children}</main>

            <Footer />
          </NextIntlClientProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
