export const mainlandData = [
  {
    key: "europe",
    title: "Европа",
    countries: ["arm", "by", "geo", "kz", "rus"],
  },
  {
    key: "asia",
    title: "Азия",
    countries: ["are", "tur"],
  },
  {
    key: "northAmerica",
    title: "Северная Америка",
    countries: [],
  },
  {
    key: "southAmerica",
    title: "Южная Америка",
    countries: [],
  },
  {
    key: "africa",
    title: "Африка",
    countries: [],
  },
  {
    key: "oceania",
    title: "Австралия и океания",
    countries: [],
  },
  {
    key: "antarctica",
    title: "Антарктида",
    countries: [],
  },
];
export const countriesData = [
  {
    id: 1,
    title: "Казахстан",
    value: "kazahstan",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "kz",
    flag: "kz.jpg",
  },
  {
    id: 2,
    title: "Россия",
    value: "russia",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "rus",
    flag: "rus.jpg",
  },
  {
    id: 3,
    title: "Беларусь",
    value: "belarus",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "by",
    flag: "by.png",
  },
  {
    id: 4,
    title: "Армения",
    value: "armenia",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "arm",
    flag: "arm.png",
  },
  {
    id: 5,
    title: "Грузия",
    value: "georgia",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "geo",
    flag: "geo.jpg",
  },
  {
    id: 6,
    title: "ОАЭ",
    value: "uae",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "are",
    flag: "are.png",
  },
  {
    id: 7,
    title: "Турция",
    value: "turkey",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
    iso: "tur",
    flag: "tur.png",
  },
];
