export const countries = [
  {
    id: 1,
    title: "Казахстан",
    value: "kazahstan",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
  },
  {
    id: 2,
    title: "Россия",
    value: "russia",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
  },
  {
    id: 3,
    title: "Беларусь",
    value: "belarus",
    videoSrc: "/mock/polandVideoMock.mp4",
    posterSrc: "/mock/restMock.jpg",
  },
];

export const mockDistrict = [
  {
    id: 1,
    title: "Алматинская область",
    value: "almatydistrict",
    img: "/mock/almatydistrict.jpeg",
    link: "/kazahstan/almatydistrict",
    videoSrc: "/mock/almatydistrict.jpeg",
    posterSrc: "/mock/almatydistrict.jpeg",
    location: "Казахстан",
  },
  {
    id: 2,
    title: "Акмолинская область",
    value: "akmolindistrict",
    img: "/mock/akmolindistrict.jpg",
    link: "/kazahstan/akmolindistrict",
    videoSrc: "/mock/akmolindistrict.jpg",
    posterSrc: "/mock/akmolindistrict.jpg",
    location: "Казахстан",
  },
  {
    id: 3,
    title: "Атырауская область",
    value: "atyraydistrict",
    img: "/mock/atyraydistrict.jpg",
    link: "/kazahstan/atyraydistrict",
    videoSrc: "/mock/atyraydistrict.jpg",
    posterSrc: "/mock/atyraydistrict.jpg",
    location: "Казахстан",
  },
  {
    id: 4,
    title: "Туркестанская область",
    value: "turkestandistrict",
    img: "/mock/turkestandistrict.jpg",
    link: "/kazahstan/turkestandistrict",
    videoSrc: "/mock/turkestandistrict.jpg",
    posterSrc: "/mock/turkestandistrict.jpg",
    location: "Казахстан",
  },
];
export const mockTowns = [
  {
    id: 1,
    title: "Алматы",
    value: "almaty",
    img: "/mock/almaty.jpg",
    link: "/kazahstan/almatydistrict/almaty",
    videoSrc: "/mock/almaty.jpg",
    posterSrc: "/mock/almaty.jpg",
    location: "Казахстан",
  },
  {
    id: 2,
    title: "Астана",
    value: "astana",
    img: "/mock/astana.jpg",
    link: "/kazahstan/akmolindistrict/astana",
    videoSrc: "/mock/astana.jpg",
    posterSrc: "/mock/astana.jpg",
    location: "Казахстан",
  },
  {
    id: 3,
    title: "Атырау",
    value: "atyray",
    img: "/mock/atyray.jpg",
    link: "/kazahstan/atyraydistrict/atyray",
    videoSrc: "/mock/atyray.jpg",
    posterSrc: "/mock/atyray.jpg",
    location: "Казахстан",
  },
  {
    id: 4,
    title: "Шымкент",
    value: "shymkent",
    img: "/mock/shymkent.jpg",
    link: "/kazahstan/turkestandistrict/shymkent",
    videoSrc: "/mock/shymkent.jpg",
    posterSrc: "/mock/shymkent.jpg",
    location: "Казахстан",
  },
];
