import { IDataCardSlider } from "@/types/ICards";

export const mockObjectsHotels: IDataCardSlider[] = [
  {
    id: 1,
    title: "Marriot",
    location: "Алматы, Казахстан",
    rating: 5,
    reviews: 20,
    type: "Отель",
    img: "/mock/hotelMock.jpg",
  },
  {
    id: 2,
    title: "Double tree by Hilton",
    location: "Атырау, Казахстан",
    rating: 5,
    reviews: 20,
    type: "Отель",
    img: "/mock/hotelMock.jpg",
  },
  {
    id: 3,
    title: "Europe",
    location: "Алматы, Казахстан",
    rating: 5,
    reviews: 20,
    type:"Отель",
    img: "/mock/hotelMock.jpg",
  },
  {
    id: 4,
    title: "National Poland Hotel",
    location: "Астана, Казахстан",
    rating: 5,
    reviews: 20,
    type:"Отель",
    img: "/mock/hotelMock.jpg",
  },
  {
    id: 5,
    title: "Bober hotel",
    location: "Актау, Казахстан",
    rating: 5,
    reviews: 20,
    type:"Отель",
    img: "/mock/hotelMock.jpg",
  },
  {
    id: 6,
    title: "Bober hotel",
    location: "Шимкент, Казахстан",
    rating: 5,
    reviews: 20,
    type: "Hotel",
    img: "/mock/hotelMock.jpg",
  },
];
export const mockObjectsCafe: IDataCardSlider[] = [
  {
    id: 1,
    title: "Embassy",
    location: "Астана, Казахстан",
    rating: 5,
    reviews: 5,
    type: "Кафе",
    additional:'$$ - $$$ • Средиземноморская, Барбекю, Европейская',
    img: "/mock/cafeMock.jpg",
  },
  {
    id: 2,
    title: "Starbacks",
    location: "Атырау, Казахстан",
    rating: 5,
    reviews: 20,
    type: "Кофейня",
    additional:'$$ - $$$ • Средиземноморская, Барбекю, Белорусская',
    img: "/mock/cafeMock.jpg",
  },
  {
    id: 3,
    title: "Varka",
    location: "Актау, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Кофейня",
    additional:'$$ - $$$ • Средиземноморская, Барбекю, Казахская',
    img: "/mock/cafeMock.jpg",
  },
  {
    id: 4,
    title: "Cofix",
    location: "Астана, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Кофейня",
    additional:'$$ - $$$ • Средиземноморская,  Американская',
    img: "/mock/cafeMock.jpg",
  },
  {
    id: 5,
    title: "Rose Gose",
    location: "Алматы, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Ресторан",
    additional:'$$ - $$$ • Средиземноморская,  Европейская',
    img: "/mock/cafeMock.jpg",
  },
  {
    id: 6,
    title: "Golden coffee",
    location: "Шимкент, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Ресторан",
    additional:'$$ - $$$ • Средиземноморская, Барбекю, Азиатская',
    img: "/mock/cafeMock.jpg",
  },
];
export const mockObjectsRelax: IDataCardSlider[] = [
  {
    id: 1,
    title: "Монумент Астана-Байтерек",
    location: "Астана, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Достопримечастельность",
    img: "/mock/restMock.jpg",
  },
  {
    id: 2,
    title: "Хан-Шатыр",
    location: "Астана, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Торговый центр",
    img: "/mock/restMock.jpg",
  },
  {
    id: 3,
    title: "Большое Алматинское озеро",
    location: "Алматы, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Водоемы",
    img: "/mock/restMock.jpg",
  },
  {
    id: 4,
    title: "Гора Кок Тобе",
    location: "Алматы, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Горы",
    img: "/mock/restMock.jpg",
  },
  {
    id: 5,
    title: "Мечеть Хазрет Султан",
    location: "Астана, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Священные места и религиозные достопримечательности",
    img: "/mock/restMock.jpg",
  },
  {
    id: 6,
    title: "Baizaar Mall",
    location: "Атырау, Казахстан",
    rating: 5,
    reviews: 50,
    type: "Торговые центры",
    img: "/mock/restMock.jpg",
  },
];
